version: '3.8'

services:
  scholarshare:
    build: .
    ports:
      - "7860:7860"
    environment:
      - HOST=0.0.0.0
      - PORT=7860
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    restart: unless-stopped
